DRIVER = fr"firefox"
PROFILE_PATH = fr"/Users/dennyweinberg/Library/Application Support/Firefox/Profiles/x1m25kig.default-release"
OUT_PATH = fr"/Users/dennyweinberg/Pictures"
ALBUM_HANDLER_MODE = fr"MOVE"
START = fr"https://photos.google.com/search/_m8_Favorites"
