DRIVER = fr"chrome"
PROFILE_PATH = fr"E:\Google Photos Backup\selenium_profile"
OUT_PATH = fr"E:\Google Photos Backup\data"
ALBUM_HANDLER_MODE = fr"MOVE"
START = fr"https://photos.google.com/search/_m8_Favorites"
